# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evalidate.proto\x12\tvalidpack\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fvalidatePayload\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x10validateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x07Greeter\x12:\n\x08SayHello\x12\x17.validpack.HelloRequest\x1a\x15.validpack.HelloReply2V\n\x08Validate\x12J\n\x0fvalidateRequest\x12\x1a.validpack.validatePayload\x1a\x1b.validpack.validateResponseb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_VALIDATEPAYLOAD = DESCRIPTOR.message_types_by_name['validatePayload']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_VALIDATERESPONSE = DESCRIPTOR.message_types_by_name['validateResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:validpack.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

validatePayload = _reflection.GeneratedProtocolMessageType('validatePayload', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEPAYLOAD,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:validpack.validatePayload)
  })
_sym_db.RegisterMessage(validatePayload)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:validpack.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

validateResponse = _reflection.GeneratedProtocolMessageType('validateResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATERESPONSE,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:validpack.validateResponse)
  })
_sym_db.RegisterMessage(validateResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
_VALIDATE = DESCRIPTOR.services_by_name['Validate']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=29
  _HELLOREQUEST._serialized_end=57
  _VALIDATEPAYLOAD._serialized_start=59
  _VALIDATEPAYLOAD._serialized_end=93
  _HELLOREPLY._serialized_start=95
  _HELLOREPLY._serialized_end=124
  _VALIDATERESPONSE._serialized_start=126
  _VALIDATERESPONSE._serialized_end=161
  _GREETER._serialized_start=163
  _GREETER._serialized_end=232
  _VALIDATE._serialized_start=234
  _VALIDATE._serialized_end=320
# @@protoc_insertion_point(module_scope)
