# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evalidate.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fvalidatePayload\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x10validateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2G\n\x07Greeter\x12<\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply2X\n\x08Validate\x12L\n\x0fvalidateRequest\x12\x1b.helloworld.validatePayload\x1a\x1c.helloworld.validateResponseb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_VALIDATEPAYLOAD = DESCRIPTOR.message_types_by_name['validatePayload']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_VALIDATERESPONSE = DESCRIPTOR.message_types_by_name['validateResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

validatePayload = _reflection.GeneratedProtocolMessageType('validatePayload', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEPAYLOAD,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.validatePayload)
  })
_sym_db.RegisterMessage(validatePayload)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

validateResponse = _reflection.GeneratedProtocolMessageType('validateResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATERESPONSE,
  '__module__' : 'validate_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.validateResponse)
  })
_sym_db.RegisterMessage(validateResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
_VALIDATE = DESCRIPTOR.services_by_name['Validate']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=30
  _HELLOREQUEST._serialized_end=58
  _VALIDATEPAYLOAD._serialized_start=60
  _VALIDATEPAYLOAD._serialized_end=94
  _HELLOREPLY._serialized_start=96
  _HELLOREPLY._serialized_end=125
  _VALIDATERESPONSE._serialized_start=127
  _VALIDATERESPONSE._serialized_end=162
  _GREETER._serialized_start=164
  _GREETER._serialized_end=235
  _VALIDATE._serialized_start=237
  _VALIDATE._serialized_end=325
# @@protoc_insertion_point(module_scope)
